name: Generate Open Data (daily)

on:
  schedule:
    - cron: "10 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Warsaw
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate CSV + manifest + MD5
        run: |
          python tools/generate_open_data.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add open-data/
          git commit -m "Daily open-data update [skip ci]" || echo "No changes"
          git push
