name: Generate Open Data (daily)

on:
  schedule:
    - cron: "10 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Warsaw
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate CSV + manifest + MD5
        run: |
          python tools/generate_open_data.py

      - name: Commit & push with PAT (only open-data)
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A open-data/
          git commit -m "Daily open-data update [skip ci]" || exit 0
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${REPO}.git
          git push origin HEAD:main
